# Generated by Django 4.2.5 on 2023-09-20 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trans_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="processed_file",
        ),
    ]
