# Generated by Django 4.2.5 on 2023-09-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans_app", "0002_remove_uploadedfile_processed_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="processed_file",
            field=models.FileField(default=None, null=True, upload_to="processed/"),
        ),
    ]
