# Generated by Django 4.2.5 on 2023-10-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans_app", "0004_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="confirmation_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
